CREATE TABLE IF NOT EXISTS `email_otp_challenges` (
  `challenge_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `challenge_token_hash` char(64) NOT NULL,
  `verification_token_hash` char(64) DEFAULT NULL,
  `purpose` varchar(32) NOT NULL,
  `email` varchar(255) NOT NULL,
  `identifier` varchar(50) NOT NULL,
  `otp_hash` varchar(255) NOT NULL,
  `expires_at` datetime NOT NULL,
  `resend_available_at` datetime NOT NULL,
  `attempt_count` tinyint unsigned NOT NULL DEFAULT 0,
  `max_attempts` tinyint unsigned NOT NULL DEFAULT 5,
  `verified_at` datetime DEFAULT NULL,
  `verification_expires_at` datetime DEFAULT NULL,
  `consumed_at` datetime DEFAULT NULL,
  `request_ip` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`challenge_id`),
  UNIQUE KEY `uq_otp_challenge_token` (`challenge_token_hash`),
  UNIQUE KEY `uq_otp_verification_token` (`verification_token_hash`),
  KEY `idx_otp_recipient_purpose` (`email`, `purpose`, `created_at`),
  KEY `idx_otp_expiry` (`expires_at`, `consumed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
