<?php
/** Maintenance recovery for generated announcement images and document PDFs. */
require_once __DIR__ . '/private_pdf_storage.php';
require_once __DIR__ . '/../config/db.php';

function uploadCanonicalPath(string $path): string
{
    return PHP_OS_FAMILY === 'Windows' ? strtolower($path) : $path;
}

/** All reads must succeed before any cleanup may begin. No schema initialization. */
function uploadReferencedFiles(PDO $pdo): array
{
    if ($pdo->inTransaction()) throw new RuntimeException('Upload reconciliation requires its own transaction.');
    $references = [];
    $pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');
    $pdo->beginTransaction();
    try {
        // Include cross-feature and embedded references, rather than assuming
        // that a generated path can occur only in its original owner's column.
        $columns = $pdo->query("SELECT c.TABLE_NAME, c.COLUMN_NAME
            FROM information_schema.COLUMNS c
            JOIN information_schema.TABLES t ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
            WHERE c.TABLE_SCHEMA = DATABASE() AND t.TABLE_TYPE = 'BASE TABLE'
              AND c.DATA_TYPE IN ('char', 'varchar', 'tinytext', 'text', 'mediumtext', 'longtext', 'json')
            ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION")->fetchAll(PDO::FETCH_ASSOC);
        if (!$columns) throw new RuntimeException('No database reference columns found; cleanup stopped.');
        $sources = [];
        foreach ($columns as $column) $sources[$column['TABLE_NAME']][] = $column['COLUMN_NAME'];
        foreach ($sources as $table => $names) {
            $quote = static fn(string $name): string => '`' . str_replace('`', '``', $name) . '`';
            $stmt = $pdo->query('SELECT ' . implode(', ', array_map($quote, $names)) . ' FROM ' . $quote($table));
            while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
                foreach ($row as $value) {
                    // JSON may escape slashes; HTML, JSON and plain text may
                    // all contain references. Extra matches conservatively keep files.
                    $normalized = preg_replace('#/+#', '/', str_replace(['\\/', '\\'], '/', (string)$value));
                    preg_match_all('#(?:uploads/(?:announcements|documents)/|documents/)[A-Za-z0-9._-]+#', $normalized, $matches);
                    foreach ($matches[0] as $stored) {
                        $path = uploadResolvePublicFile($stored, 'announcements')
                            ?? privatePdfResolveStoredFile($stored, ['documents', 'print-jobs']);
                        if ($path) $references[uploadCanonicalPath($path)] = true;
                    }
                }
            }
        }
        $pdo->commit();
        return $references;
    } catch (Throwable $e) {
        try {
            if ($pdo->inTransaction()) $pdo->rollBack();
        } catch (Throwable $rollbackError) {
            error_log('[upload recovery] Reference-scan rollback failed: ' . $rollbackError->getMessage());
        }
        throw $e;
    }
}

/** Deletion is for a drained maintenance window, never a live application. */
function uploadReconcileDirectory(string $directory, array $references, bool $delete = false, ?int $now = null): array
{
    $root = realpath($directory);
    if ($root === false) return [];
    $cutoff = ($now ?? time()) - 172800;
    $results = [];
    foreach (new DirectoryIterator($root) as $entry) {
        if ($entry->isDot() || $entry->isLink() || !$entry->isFile()) continue;
        // Only names generated by this upload writer; leave legacy/manual files alone.
        if (!preg_match('/^[A-Za-z0-9_-]+_[a-f0-9]{32}\.(?:pdf|png|jpg|gif|webp)$/', $entry->getFilename())) continue;
        $path = $entry->getRealPath();
        if (!$path || $entry->getMTime() > $cutoff || isset($references[uploadCanonicalPath($path)])) continue;
        $result = ['path' => $path, 'bytes' => $entry->getSize(), 'deleted' => false];
        if ($delete) {
            if (!unlink($path)) throw new RuntimeException('Could not remove orphan: ' . $path);
            $result['deleted'] = true;
        }
        $results[] = $result;
    }
    return $results;
}
